# Generated by Django 4.2.8 on 2026-05-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.genders'),
        ),
    ]
