# Generated by Django 4.2.8 on 2026-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_users_profile_picture_alter_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('email', models.EmailField(blank=True, max_length=55)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_admins',
            },
        ),
    ]
